language: c

os: linux
dist: focal

before_install:
  - sudo apt-get install -y dput acl-dev libx11-dev libxext-dev libcap-dev

git:
  depth: 1

jobs:
  include:
    - stage: "Build test"
      script: ./build.sh && ./install-to-home.sh
    - stage: "Deploy packages"
      script: ./create-debian-source.sh
