language: c

os: linux
dist: focal

before_install:
  - sudo apt-get install -y acl-dev libx11-dev libxext-dev

git:
  depth: 1

jobs:
  include:
    - stage: "test build"
      script: ./build.sh
      script: ./install-to-home.sh
    - stage: "deploy"
      script: ./create-debian-source.sh
