language: c

before_install:
  - sudo apt-get install -y dput acl-dev libx11-dev libxext-dev libcap-dev

git:
  depth: 1

test: &test
  stage: "Build test"
  script: ./build.sh && ./install-to-home.sh

deploy: &deploy
  stage: "Deploy packages"
  script: ./create-debian-source.sh

jobs:
  include:
    - <<: *test
      os: linux
      dist: focal
    - <<: *test
      os: linux
      dist: bionic
    - <<: *test
      os: linux
      dist: xenial

    - <<: *deploy
      os: linux
      dist: focal
    - <<: *deploy
      os: linux
      dist: bionic
    - <<: *deploy
      os: linux
      dist: xenial