#!/bin/sh

# perform some basic setup for fresh debian_chroot
# intended for run with debian-setup profile

set -e

# minimal setup
apt-get update
apt-get install dialog -y
if apt-get install locales-all -y; then
  #try to use pregenerated locales to avoid this bug: https://bbs.archlinux.org/viewtopic.php?id=228776
  apt-get purge locales -y
else
  #fallback to locales package, that needs to be periodically regenerated by running locale-gen
  apt-get install locales -y
  dpkg-reconfigure locales
fi
apt-get install apt-utils -y
dpkg-reconfigure dialog
dpkg-reconfigure apt-utils
apt-get install tzdata -y
dpkg-reconfigure tzdata

# try remove snapd
apt-get remove --purge snapd -y || true
apt-get autoremove --purge -y || true

# dist-upgrade
apt-get dist-upgrade -y

# additional packages for dbus, x11, mesa, pulse integration and package management gui (synaptic) with minimal x11 stack
apt-get install -y procps net-tools mc libpulse0 mesa-utils lsb-release wget adwaita-icon-theme synaptic xauth gnupg2 apt-transport-https less psmisc lsof
apt-get install -y adwaita-icon-theme-full || true
apt-get install -y apt-xapian-index || true
update-apt-xapian-index || true
